services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gobank_db
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5001:5432"

volumes:
  postgres-db:
    driver: local